a = input("enter your name:")
b = input("enter your age:")
c = input("enter your Branch:")
d = input("enter your semester:")
print("Student Information manager")
print("Name:", a)
print("Age:", b)
print("Branch:", c)
print("Semester:", d)